[Feature] TransformWithInline
reactivemarbles/DynamicData pull request #636
Opened 2022-08-31 07:21 UTC by tomasfil

Adds TransformWithInline update. 

Resolves #323

2022-09-06 11:00 UTC, RolandPheasant requested changes
Sorry for the delay in responding. Thanks for this, and would you mind adding some unit tests

2022-09-13 08:29 UTC, tomasfil commented
Sorry for delay from me as well. I am very busy past few days. I will try my best to add unit tests asap as I am able to

2022-09-13 09:59 UTC, RolandPheasant commented on src/DynamicData/Cache/ObservableCacheEx.cs
> +    public static IObservable<IChangeSet<TDestination, TKey>> TransformWithInlineUpdate<TDestination, TSource, TKey>(this IObservable<IChangeSet<TSource, TKey>> source, Func<TSource, Optional<TSource
You could combine these 2 overloads into one by making the error handler an optional param.

2022-09-26 15:28 UTC, SuperJMN commented
> Adds TransformWithInline update.
> 
> Resolves #323

I've created a sample to see this working: https://github.com/SuperJMN-Tutorials/TreeDataGrid-InlineUpdate-WithGrouping

2022-10-05 13:16 UTC, tomasfil commented
Hello @RolandPheasant, I did manage to add some tests and I hope it is sufficient.

2022-10-05 15:05 UTC, merged

2022-10-05 15:05 UTC, RolandPheasant commented
This is great thanks.

2022-10-05 15:13 UTC, SuperJMN commented
Thanks! I'll use this ASAP.