Feature:  MergeManyChangeSets for Cache ChangeSets with List ChangeSets
reactivemarbles/DynamicData pull request #790
Opened 2023-12-10 20:00 UTC by dwcullop

## Description

Implements the `MergeManyChangeSets` operator for Cache ChangeSets source and List ChangeSet children.

2023-12-13 08:00 UTC, RolandPheasant requested changes

2023-12-13 08:03 UTC, RolandPheasant commented
Code wise, it looks great and only one minor request which is to seal classes when possible.

Aside from that I ran the stress tests and managed to produce some intermittent errors.

![image](https://github.com/reactivemarbles/DynamicData/assets/9879866/219955e5-658f-4327-9bb4-81134e46538b)

and on a subsequent run 

![image](https://github.com/reactivemarbles/DynamicData/assets/9879866/bc71dc2c-6155-4d91-8f03-0a4ef31dd475)

I think the stress tests are a brilliant idea, but I wonder whether that test performance wizard @JakenVeina has any suggested how those tests can be made to run fast,

2023-12-14 06:33 UTC, JakenVeina commented
> I think the stress tests are a brilliant idea, but I wonder whether that test performance wizard @JakenVeina has any suggestions how those tests can be made to run fast,

Would be happy to, if the branch would build. ;)

2023-12-14 08:01 UTC, ChrisPulman commented on src/DynamicData/List/Internal/MergeManyListChangeSets.cs
> +internal class MergeManyListChangeSets<TObject, TDestination>(IObservable<IChangeSet<TObject>> source, Func<TObject, IObservable<IChangeSet<TDestination>>> selector, IEqualityComparer<TDestination>?
This has been resolved

2023-12-14 08:19 UTC, ChrisPulman commented
The problem now is that the Stress tests take an infinite period of time to run.

2023-12-14 08:21 UTC, ChrisPulman commented on src/DynamicData.Tests/Cache/ToObservableChangeSetFixture.cs
> +        results.Messages.Count.Should().Be(6, "6 item sets were emitted by the source, 3 of which triggered followup evictions");
Please check why this was changed from 6 to 9, I reverted the value to 6 to make the test pass but need to be sure what the correct value should be

2023-12-14 08:28 UTC, ChrisPulman commented
> > I think the stress tests are a brilliant idea, but I wonder whether that test performance wizard @JakenVeina has any suggestions how those tests can be made to run fast,
> 
> Would be happy to, if the branch would build. ;)

@JakenVeina The branch should build now, if you have time

2023-12-15 01:47 UTC, dwcullop commented on src/DynamicData.Tests/Cache/ToObservableChangeSetFixture.cs
> +    [Fact(Skip = "Outstanding bug, notifications are not synchronized, initial item emits after error")]
Not sure the status of this.  @ChrisPulman added that change to make the unit tests pass, but I'm not sure why they were failing.

2023-12-15 01:51 UTC, dwcullop commented
> Code wise, it looks great and only one minor request which is to seal classes when possible.

Agree about sealing the classes.  Will do.

> Aside from that I ran the stress tests and managed to produce some intermittent errors.

Been fighting these for a few days now, but I hope I've got them under control now.
 
> I think the stress tests are a brilliant idea, but I wonder whether that test performance wizard @JakenVeina has any suggestions how those tests can be made to run fast,

I'm open to any suggestions.

2023-12-15 12:20 UTC, ChrisPulman commented on src/DynamicData.Tests/Cache/ToObservableChangeSetFixture.cs
> +    [Fact(Skip = "Outstanding bug, notifications are not synchronized, initial item emits after error")]
SourceErrorsImmediately_SubscriptionReceivesError has been re-enabled I ran it on repeat for an extensive period with no failures, it was Skipped on the 9th Dec (First drop of MergeManyChangeSets for List to Cache) after some major reworks to the tests in this file. I have a feeling the test may have been skipped to then come back and fix the issue causing the failure, which looks like Darrin has successfully done.

2023-12-15 12:24 UTC, ChrisPulman commented on src/DynamicData.Tests/Utilities/AddRemoveStressTester.cs
> +internal static class AddRemoveStressTester
This has been resolved

2023-12-16 09:45 UTC, RolandPheasant approved these changes
I have not followed the entire conversation on Slack, owning to being away for a couple days. Instead for now I'll approve and leave to the discretion of @dwcullop whether it is ready to be merged.

2023-12-16 19:29 UTC, merged